# Generated by Django 3.0.8 on 2020-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileClaimVehicleTheft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('occupation', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.IntegerField(db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('vehicle_registration', models.CharField(db_index=True, max_length=100)),
                ('vehicle_make', models.CharField(choices=[('toyota', 'Toyota')], db_index=True, default='', max_length=200)),
                ('manufactured_year', models.CharField(choices=[(1970, '1970'), (1980, '1980'), (1990, '1990'), (2000, '2000'), (2010, '2010'), (2020, '2020')], db_index=True, max_length=200)),
                ('hp_loan_agreements', models.BooleanField(default=True)),
            ],
        ),
    ]
