# Generated by Django 3.0.8 on 2020-08-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileclaimvehicletheft',
            name='vehicle_make',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('mazda', 'Mazda'), ('renault', 'Renault'), ('ford', 'Ford'), ('dansun', 'Datsun')], db_index=True, default='', max_length=200),
        ),
    ]
