# Generated by Django 3.0.8 on 2020-08-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_auto_20200802_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileclaimvehicletheft',
            options={'ordering': ('name',), 'verbose_name': 'car_theft_claim', 'verbose_name_plural': 'car_theft_claims'},
        ),
    ]
